data:
  training: 'A:\Projects\ML-for-Weather\data\raw\test_simple.csv'
  inference: 'A:\Projects\ML-for-Weather\data_dvc\raw\pseudo_inference.csv'
date:
  start: '2019-01-01'
  end:  '2020-01-01'
vars_old:
  temp: 'temperature_air_mean_200'
  cloud: 'cloud_cover_total'
vars_new:
  temp: 'temperature'
  cloud: 'cloud_cover'
transform:
  vars: ['temperature', 'cloud_cover', 'wind_speed']
diff:
  diff: [1,2]
  lags: [1,2,3]
  #lags: [1,2,3,4,5,6,9,12,24]
model:
  target: temperature
  # if no predictors are provided (i.e empty list []), all lagged vars are used
  # if predictors are given, 'month', 'day' and 'hour' always must be given. Remember to also adjust diff.lags
  predictors: []
  #predictors: ['temperature_lag_1', 'temperature_lag_2', 'temperature_lag_3', 'temperature_lag_4', 'temperature_lag_5',
  #            'temperature_lag_6', 'temperature_lag_9', 'temperature_lag_12', 'temperature_lag_24']
  #predictors: ['month', 'day', 'hour', 'temperature_lag_1', 'cloud_cover_lag_1', 'wind_speed_lag_1',
  #             'temperature_velo_1_lag_1', 'temperature_velo_1_lag_2', 'temperature_velo_2_lag_2', 'cloud_cover_acc_2_lag_2']
         
cv:
  n_splits: 5 # Specify splitting for Time series cross validation
elastic_net:
  alpha: [0.3, 0.4, 0.5, 0.6]
  l1_ratio: [0.3, 0.4, 0.5, 0.6]
svm:
  C: [0.1, 1, 10, 100, 1000]
  gamma: [1, 0.1, 0.01, 0.001, 0.0001]
  kernel: ['rbf']
xgb:
  n_estimators: [100, 400, 800]
  max_depth: [3, 6, 9]
  learning_rate: [0.05, 0.1, 0.20]
  min_child_weight: [1, 10, 100]
inference:
  end_date: "2020-01-02 21:00:00"
  models:
    

