data:
  path: 'A:\Projects\ML-for-Weather\data\raw\test_simple.csv'
vars_old:
  temp: 'temperature_air_mean_200'
  cloud: 'cloud_cover_total'
vars_new:
  temp: 'temperature'
  cloud: 'cloud_cover'
  wind: 'wind_speed'
predictors:
  vars: ['temperature', 'cloud_cover', 'wind_speed']
diff:
  lags: [1,2,24]
  velo: [1,2]
  acc: [1]

