data:
  path: 'A:\Projects\ML-for-Weather\data\raw\test_simple.csv'
vars_old:
  temp: 'temperature_air_mean_200'
  cloud: 'cloud_cover_total'
vars_new:
  temp: 'temperature'
  cloud: 'cloud_cover'
transform:
  vars: ['temperature', 'cloud_cover', 'wind_speed']
diff:
  diff: [1,2]
  lags: [1,2,24]
model:
  target: ['temperature']
  # if no predictors are provided, all lagged vars are used
  predictors: ['month', 'day', 'hour', 'temperature_lag_1',
              'cloud_cover_lag_1', 'wind_speed_lag_1']
cv:
  n_splits: 5

